tags:
  db: true
  platformdb: false

replicaCount: 1

image:
  repository: containerum/volume
  tag: v1.0.0
  pullPolicy: IfNotPresent
  secret:

service:
  port: 4343
  targetPort: 4343
  externalIP:

env:
  global:
    MODE: debug
    LOG_LEVEL: 3
    DB_USER: "volume-manager"
    DB_SSLMODE: "false"
    DB_BASE: "volume-manager"
    LISTEN_ADDR: ":4343"
  local:
    DB_HOST: "postgres:5432"
    KUBE_API_ADDR: "kube-api:1214"
    BILLING_ADDR: "billing-manager:5000"
    DB_PASSWORD:


postgresql:
  persistence:
    enabled: false
  postgresDatabase: volume-manager
  # postgresUser: postgres
  # postgresPassword: password
