[prune]
  go-tests = true
  unused-packages = true
  non-go = true

 [[prune.project]]
    name = "github.com/containerum/utils"
    non-go = false

  [[prune.project]]
      name = "github.com/containerum/kube-client"
      non-go = false

  [[prune.project]]
      name = "github.com/containerum/cherry"
      non-go = false

[[constraint]]
  name = "github.com/containerum/cherry"
  version = "~1.0.1"

[[constraint]]
  name = "github.com/containerum/kube-client"
  version = "0.19.1"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "^6.13.5"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.5"

[[constraint]]
  name = "github.com/containerum/bill-external"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/resty.v1"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/containerum/utils"
  version = "~1.0.0"

